### ISSUE TITLE
ERROR occured: Unable to create an account.

### ISSUE THREAD

**Issue by Lukemul6** [rtunazzz/SoleboxAccountGenerator#2]
The account gen gets this error,  
![image](https://user-images.githubusercontent.com/56521521/69112699-c30a5480-0a35-11ea-870e-5c4f513a26c5.png)

**Comment by rtunazzz** [comment]
![image](https://user-images.githubusercontent.com/38296319/69145978-209eaf80-0acf-11ea-84e5-d4a1bf911b05.png)

Usually it takes a couple of tries to get some accounts genned since Solebox is pretty strict and you get Forbidden errors for pretty much no reason and quickly. I added some simple proxy testing so try now and let me know if that helped! Sometimes you also run into Cloudfare (captcha) which means that the creation fails as well...
